# title of website
title: 凌凌漆导航

# description of website
description: 凌凌漆导航-影视资源导航

# favicon of website
favicon: "https://github.com/shiqiao0311.png?size=40"

# your website url
url: https://shiqiao0311.github.io/shiqiao0311.github.io/

# github profile url
github: "https://github.com/shiqiao0311/shiqiao0311.github.io/blob/gh-pages/config.yml"

# footer message
footer: © 2023-2024 凌凌漆导航

# template(theme) of your site, available:
# 1. webstack (http://webstack.cc)
template: webstack

# Google analytics
google_analytics: "G-EXE1PJ8CR2"

webstack:
  search:
    enabled: true
    default: baidu
    # 可选的搜索引擎
    engines:
      - google
      - github
      - weibo
      - baidu
      - bilibili
      - zhihu

content:
  categories:
    - name: 在线
      sites:
        - name: 555电影
          description: 最新电影、电视剧、动漫、综艺、纪录片、预告片，实时聚合全网优质影视资源，高清1080P 4K在线观看、下载、磁力。
          url: https://www.555app.vip/
        - name: 雪糕TV
          description:  雪糕TV初恋般清爽甜蜜免费高清电影电视剧综艺极速在线观看！
          url: https://www.xgitv.com/
        - name: 飘花播播
          description: 飘花播播集合飘花飘雪影院分享热门电影、电视剧、综艺、动漫、飘雪网国产、日本、韩国在线观看免费观看在线观看！
          url: https://www.7itv.com/
        - name: LIBVIO
          description: 
          url: https://www.libvio.me/
        - name: 6080
          description: 6080精彩视频在线看
          url: https://www.6080wu.com/
        - name: 首播站
          description: 首播站提供最新最快的电影和电视剧在线免费观看！
          url: https://shoubozhan.com/
        - name: 凯奇影院
          description: 凯奇影院-是全球华人在线视频媒体平台,即点即播,无广告无VIP!免费提供2023最新高清的电影,电视剧,综艺,动漫,台劇,日劇,泰劇等.提供最新影视资讯中文网,最新热播电影在线免费观看,给您免费的试听享受
          url: https://fsnet123.com/
        - name: COKEMV
          description: COKEMV影视(cokemv.fun)是一個能够让你可以轻松观看更多十分热门的影视剧，更多精彩的影视剧资源免费的为你进行播放，无广告轻松的进行看剧
          url: https://www.cokemv.fun/
        - name: 蛋蛋赞影院
          description: 蛋蛋赞影院全球唯一不用安装播放器的在线电影网,每天第一时间更新
          url: https://dandanzan.net/
        - name: 看片狂人
          description: 看片狂人(www.kpkuang.fun)是一个为影迷剧迷朋友们建立的可免费在线观看,免费超前点播,下载高清视频资源的网站,每日收集全网最新的电影,电视剧,动漫,综艺,日剧,韩剧,美剧等高清资源供网友免费观看和下载。
          url: https://one.kpkuang.vip/
        - name: 高分电影网
          description: 高分电影高分影院最新免费在线观看电影手机看片
          url: https://www.gaofen3.com/
        - name: 97影院
          description: 97影院是可以免费观看最新电影和同步热播电视剧的极速影院，同时还提供高清电影下载，最新最全的美剧每天第一时间更新，97影院是您观看在线电影的最佳选择！
          url: https://www.97so.cc/
        - name: 追剧兔
          description: 追剧兔-提供最新最快的视频分享数据
          url: https://www.zjtu.cc/
        - name: 厂长资源
          description: 厂长资源(CZZY)为您提供海量1080p经典影视免费观看！
          url: https://www.czzy55.com/
        - name: 兄弟影视
          description: 兄弟影视(brovod.com)是一家免费全球影视资源在线观看的平台,拥有海量、优质、超清蓝光电影和全球的电视剧,高画质在线动漫。专业全网收集最新,最好看的电视剧、高清电影、经典动漫、综艺娱乐节目，兄弟影视以丰富的内容、极致的观看体验、便捷的高速播放、24小时多平台无缝应用体验以及快捷!
          url: https://www.brovod.com/
        - name: 秋霞影视
          description: 【秋霞影视】www.qiuxia678.com官方提供最新热播电视剧全集未删减【超前点播】，最新热映电影、海量vip高清电影【无广告不卡顿】，好看搞笑的综艺节大全、经典动漫全集服务，并提供最新好看的韩剧、日剧、美剧等海外电视剧。
          url: https://www.kkw361.com/
        - name: Nike影视网
          description: Nike影视网(www.ajeee.com)提供最新最全面的热门电影,热门电视剧大全,热门综艺,动漫影院及午夜恐怖片,动作片,喜剧片等视频在线观看（视频无广告弹窗）
          url: https://ajeee.com/
        - name: 蓝光影院
          description: 蓝光影院为您提供2022最新电视剧、好看的电视剧、最新电影、影视大全，蓝光视频免费在线观看服务，无广告不卡，每天第一时间更新！
          url: https://www.lgyy.fun/
        - name: 红标影院
          description: 红标影院以好看的电影及热门电影大全作为基础,红标影院实时刷新最新电影排行榜,最新电影更新速度最快,哒哒哒电影免费观看在线高清视频引领不用下载播放器的时代！
          url: https://www.cncydw.com/
        - name: 七味
          description: 七味观影小站
          url: https://www.mp4do.com/
        - name: 豌豆PRO
          description: 
          url: https://wandou.la/
        - name: 两个BT
          description: 两个BT免费为网友提交BT种子下载，免费电影资源下载，以及各种高清电影在线观看,最全的最新电视剧，最近上映热门电影下载。韩国电视剧、香港TVB电视剧、韩剧、日剧、美剧、动漫番剧。
          url: https://www.bttwo.net/
        - name: 三米影视
          description: 三米影视是为山东智邦有限公司提供最新电影,电视剧手机观看,神马影院我不卡,韩国伦理福利电影,以及热播动漫，综艺，明星资料，演员表，剧情，资讯等，无弹窗、速度快、每天第一时间更新，最新好看的电视剧大全及时快速的影视推荐。
          url: https://www.lyzhibang.com/
        - name: 青苹果影院
          description: 青苹果影院为大家提供最新最快的院线电影、热播电视剧免费在线观看,每日最快更新最新韩剧、日剧、美剧!看电影就到青苹果影院!
          url: https://www.zgyhbct.com/
        - name: 电影先生
          description: 电影先生聚合全网影片，你想看的全都有！电影先生每天搜集互联网最新电影和电视剧，为广大用户免费提供无广告在线观看电影和电视剧服务，及时收录最新、最热、最全的电影大片,高清正版免费看。
          url: https://dianying.im
        - name: 6v电影
          description: 6v电影（www.hao6v.tv），每天搜集互联网最新电影和电视剧，为使用迅雷软件的用户提供最新的电影、电视剧、高清电影、免费下载等服务。
          url: https://www.6v520.com/
        - name: 秒搜影视
          description: 秒搜影视提供好看的首映最新热播电影,全集电视剧,综艺,动漫,高清美剧手机在线观看和剧情介绍,星辰影视网全天24小时在线更新,让大家以最快的速度享受视觉上的盛宴!
          url: https://www.mashyzn.com/
        - name: 电影天堂
          description: 【电影天堂】天天搜集分享全网最新无删减好看的电影,2024最新热播vip电视连续剧免费看,热门综艺娱乐节目、经典动漫等高清完整版视频资源,看视频,上电影天堂就够了
          url: https://www.gzljx.com/
        - name: 电影频道
          description: 电影频道是影视眼的热门频道之一，超全的电影大全，新电影每天第一时间更新，放送最新好看的免费电影。看最新电影、好看的电影就上影视眼电影频道。
          url: https://www.jbbsjzx.com/dy.html
        - name: 小吉影院
          description: 星辰影院为您提供2022最新电视剧、电视剧大全、好看的电视剧、每天更新最新好看的电视剧，最新综艺真人秀，明星信息与相关电影电视剧，同时提供电影演员表、电视剧演员表，角色等相关内容，是影视爱好者们的电影天堂www.qiujingjc.com
          url: https://www.xinyi123.com/
        - name: 大师兄影视
          description: 大师兄影视工厂收集全网影视蓝光高清资源，全部免费VIP在线观看，即点即播，无广告水印，看电影找大师兄！
          url: https://233s.com/
        - name: 神马影视
          description: 神马影视为您提供2024最新电视剧、电视剧大全、好看的电视剧、最新的电影在线观看和迅雷电影下载，每天更新最新好看的电视剧，最新综艺真人秀，明星信息与相关电影电视剧，同时提供电影演员表、电视剧演员表，角色等相关内容，是影视爱好者们的电影天堂
          url: https://www.scksj.cn/
        - name: 蓝鲸TV
          description: 蓝鲸TV为您提供最新电影,好看的电影,热播电视剧大全,经典动漫推荐,综艺娱乐等免费高清视频完整版在线观看。
          url: https://m.4abd.com/
        - name: 龙腾影院
          description: 龙腾影院是一个免费看vip电影电视剧的网站，拥有海量、优质、高清电影和好看的电视剧，搞笑综艺及新番动漫，无须会员即可无广告观看全网影视作品，看电影来龙腾影院准没错。
          url: https://www.longtenghb.com/
        - name: 奇热777电影网
          description: 奇热777电影网为您提供热播电视剧、电视剧分集剧情介绍、演员表、人物大结局以及热门电影、综艺节目、动漫、明星资料等影视相关资讯。
          url: https://www.qire777.com/
        - name: 52影视网
          description: 52影视网(www.52ys.cc)为大家提供各种类型电影,热播电视剧,综艺节目,动漫以及限制级电影免费在线观看,52影视网还支持手机在线观看,非常方便,希望大家喜欢。
          url: https://www.52ys.cc/
        - name: 海蓝影院
          description: 海蓝影院提供最全的最新电影大片，最热电视剧，韩国电视剧、香港TVB电视剧、韩剧、日剧、美剧、综艺、动漫的在线观看，无需下载任何播放器即可在线免费观看，每天第一时间更新，欢迎影迷到爱豆影视来看最新好看的高清免费电视剧。
          url: https://www.hailan.tv/

    - name: 解析
      sites:
        - name: 哔哩哔哩(bilibili)视频解析下载
          description: 哔哩哔哩高清视频解析下载工具是一个免费的B站视频在线解析提取工具,支持提取B站APP和bilibili网站上的任何视频,提取出来的视频无水印.我们可以借助此下载器方便地将视频保存到手机相册或者电脑硬盘.
          url: https://bili.iiilab.com/
        - name: B站视频下载工具 | 极简纯净
          description: b站视频下载工具，免费极简方便
          url: https://zhouql.vip/bilibili/

    - name: GitHub
      sites:
        - name: 我的电视（MY TV）
          description: 电视直播软件，安装即可使用
          url: https://github.com/lizongying/my-tv
        - name: Buzz
          description: Ai视频语音转文字
          url: https://github.com/chidiwilliams/buzz
        - name: WeChatMsg
          description: 提取微信聊天记录，将其导出成HTML、Word、CSV文档永久保存，对聊天记录进行分析生成年度聊天报告
          url: https://github.com/LC044/WeChatMsg
        - name: bililive-go
          description: Bililive-go是一个支持多种直播平台的直播录制工具
          url: https://github.com/hr3lxphr6j/bililive-go
        - name: liveRecordAuto
          description: 直播复盘录制工具
          url: https://github.com/OriX6/liveRecordAuto
        - name: GitHub520
          description: 解决访问时图裂、加载慢的问题。
          url: https://github.com/521xueweihan/GitHub520
        - name: SwitchHosts
          description: SwitchHosts 是一个管理 hosts 文件的应用
          url: https://github.com/oldj/SwitchHosts
          
    - name: 装机
      sites:
        - name: 联想知识库
          description: 
          url: https://iknow.lenovo.com.cn/tool/lists?
        - name: 专注于Win7
          description: 专注于Win7系列作品是吻妻出品(newxitong.com),一直专注于win7,致力于分享最新最好用的Windows7纯净旗舰版系统下载,而吻妻是一位有态度,有原则的不随波逐流的系统爱好者。
          url: https://www.newxitong.com/
        - name: 专注于Win10
          description: 也许是迄今为止最好的Windows——Windows10,现已推出吻妻优化作品,一如既往的品质更稳定更好用的win10纯净版系统欢迎你下载体验。
          url: https://iwin10.net/
        - name: HelloWindows.cn
          description: HelloWindows是一个完整极致的Windows纯净系统下载站，不夹带任何私货，系统全部来源于微软官方原版，本站只是收录官方发布的系统以及工具，方便大家下载，请放心使用。永久在线：www.hellowindows.cn
          url: https://hellowindows.cn/
        - name: 图吧工具箱
          description: 图吧工具箱，是开源、免费、绿色、纯净的硬件检测工具合集，专为所有计算机硬件极客、DIY爱好者、各路大神及小白制作。集成大量常见硬件检测、评分工具，一键下载、方便使用。
          url: https://www.tbtool.cn/
        - name: 山己几子木
          description: 本站提供 Windows 11、Windows 10、Windows 8.1、Windows 8、Windows 7、Windows XP 的 MSDN 镜像资源展示。
          url: https://msdn.sjjzm.com/
        - name: 系统库
          description: 系统库，免费为你提供我告诉你msdn原版纯净系统，原版win11，win10，win8/8.1，win7系统下载，原版office全系列下载与安装等服务
          url: https://www.xitongku.com/
        - name: 我告诉你
          description: 
          url: https://msdn.itellyou.cn/
        - name: 驱动总裁
          description: 驱动总裁是由系统总裁自主开发的一款硬件驱动智能安装软件，集在线和离线双模式的综合驱动工具，在线拥有庞大的驱动库，离线拥有体积适中的驱动包，即是系统封装人士的专业首选，亦是普通用户的不二之选！
          url: https://www.sysceo.com/dc.html
        - name: 360驱动大师
          description: 360驱动大师是一款专业解决驱动安装更新软件，百万级的驱动库支持，驱动安装一键化，无需手动操作，首创的驱动体检技术，让你更直观了解您电脑的状态，强大的云安全中心让保证您所下载的驱动不带病毒，快一点，再快一点，体验一键化安装和升级的乐趣，驱动大师陪你一路行。
          url: https://dm.weishi.360.cn/home.html?from=homepage
        - name: Geek
          description: 一个强大的卸载工具，没有强制用户的更新，geek卸载软件一直是完全免费的，也可以付费支持作者，正常安装和卸载的时候，都可以用geek找到相关的卸载方法，除非这个软件或者游戏是没有卸载的，需要手动完全删除，这种情况geek是真的完全没有办法了。
          url: https://geekuninstaller.com/

    - name: 接口
      sites:
        - name: 饭太硬
          description: 
          url: http://www.饭太硬.top/tv/
    - name: 下载
      sites:
        - name: Grab4K
          description: Grab4K专注电影、电视剧、动漫、演唱会等4K蓝光原盘资源下载，每日更新。
          url: https://www.grab4k.com/
        - name: 电影天堂
          description: 最好的迅雷电影下载网，分享最新电影，高清电影、综艺、动漫、电视剧等下载！
          url: https://www.dy2018.com/
        - name: 皮皮虾资源
          description: 
          url: https://ppxzy.net/
        - name: 中国蓝光网
          description: 高清蓝光网专注于蓝光高清电影，每日为大家提供最新的1080P高清电影和蓝光原盘资源下载！这里是高清影视发烧友的电影天堂。
          url: https://www.languangdy.com/
        - name: 新剧坊
          description: 新剧坊收集互联网上热播电视剧，好看电影，最新动漫、综艺等影视和其他类的百度网盘资源，为大家提供一个百度云网盘的免费下载平台，提供各类影视百度网盘资源下载。
          url: https://www.xinjuc.com/
        - name: 高清电影天堂
          description: 高清电影天堂，每天关注提供720p电影、1080p电影、蓝光原盘电影、3D高清电影、高清mp4电影，最新热门bt种子磁力链迅雷电影下载网站，是下载了解高清电影天堂！
          url: https://www.gaoqing888.com/
        - name: 中国高清网
          description: 中国高清网是每天关注提供720p高清、1080p高清、蓝光原盘高清、4K高清、最新热门bt种子磁力链迅雷下载网站，是下载了解高清电影的天堂！
          url: https://gaoqing.la/
        - name: MINI4K迷客电影
          description: mini4k迷客电影，每日更新最新电影资源，最专业电影推荐，2160P、4K等超高清分辨率电影迅雷下载、百度网盘下载，提供bt种子和磁力链接下载资源。
          url: https://www.mini4k.com/
        - name: 蜂鸟影院
          description: 蜂鸟影院(www.juchecheng.com)实时聚合热门电影、电视剧、综艺、动漫等优质影视资源免费在线观看,手机追剧看片一个都不少
          url: https://www.juchecheng.com/
    - name: 游戏
      sites:
        - name: Wavse
          description: Wavse,单机游戏下载网站,提供最新,热门的单机游戏下载,无需网盘即可满速下载,每天更新游戏资源。
          url: https://wavse.com/
        - name: FreeGamesDL
          description: Download New Action, FPS Shooter, Adult, Adventure, RPG, Simulation, Racing, VN, Sports, Strategy Cracked &amp; Free PC Steam Games + Updates.
          url: https://www.freegamesdl.net/
        - name: Switch520
          description: switch游戏下载-PC游戏下载-switch破解游戏下载-PC破解游戏下载-Switch520-xxxxx520
          url: https://www.gamer520.com/
        - name: switch520
          description: switch520全球游戏网可以白嫖switch游戏下载，switch520全球游戏网可以提供ps4游戏下载，switch破解游戏下载，ps4破解游戏下载，还可以白嫖ds游戏下载，psv游戏下载，xbox游戏下载，ps4游戏下载，还有全球热门steam破解游戏，pc破解游戏下载，可以让您享受最全最热门的游戏下载服务。
          url: https://www.520switch.com
        - name: GBT乐赏游戏空间
          description: 
          url: http://gbtgame.ysepan.com/

    - name: 网盘
      sites:
        - name: 网盘搜索,就上盘搜搜
          description: 盘搜搜官网支持百度云搜索、115网盘、360云盘、华为网盘、新浪微盘等搜索服务，是您工作、学习、娱乐的网盘搜索神器。
          url: https://pansoso.com/
        - name: SOSO云盘搜索导航
          description: SOSO云盘导航，为大家免费提供最新的网盘搜索网站导航平台，支持百度网盘、迅雷网盘、阿里云盘，蓝奏云盘、迅雷网盘，天翼网盘、腾讯微云、UC网盘，飞猫云盘、移动和彩云网盘、等十大网盘..
          url: https://www.sosoyunpan.com/
        - name: 网盘搜索
          description: 盘58网盘搜索引擎支持百度网盘搜索、阿里云网盘搜索、夸克网盘搜索等云搜索服务，实时收录最新各类网盘资源，为您提供专业的网盘搜索服务。
          url: http://www.pan58.com/
          
    - name: 软件
      sites:
        - name: 软仓丨RuanCang.Net
          description: 软仓是一个集合专业软件的导航网站，免费下载供学习使用，本站承诺无毒无广告，纯公益项目，不以此盈利
          url: https://ruancang.net/#/
          
    - name: AI
      sites:
        - name: 秘塔AI搜索
          description: 
          url: https://metaso.cn/
        - name: 写作猫
          description: 
          url: https://xiezuocat.com/
          
    - name: 配音
      sites:
        - name: TTSMaker在线免费文字转语音
          description: TTSMaker（马克配音）是一款免费的文本转语音工具，提供语音合成服务，支持多种语言，包括中文、英语、日语、韩语、法语、德语、西班牙语、阿拉伯语等50多种语言，以及超过300种语音风格。您可以用它制作视频配音，也可用于有声书朗读，或下载音频文件用于商业用途（完全免费）。作为一款优秀的AI配音工具，TTSMaker可以轻松地将文本转换为语音。
          url: https://ttsmaker.cn/
          
    - name: 搞机
      sites:
        - name: 搞机助手
          description: 发现更多实用软件，尽在lsdy.top
          url: https://lsdy.top/
        - name: 小米ROM
          description: XiaomiROM.com 是一个站点，用于收集小米手机、小米平板等小米机型其国行版、全球版、欧洲版（欧版）、印度版、印度尼西亚版、俄罗斯版（俄版）、土耳其版、台湾版（台版）、日本版（日版）的小米ROM。刷机包下载链接来自小米ROM官网地址，您可以全速下载到安全可靠的固件。固件均为小米官方ROM，当前没有第三方 ROM。
          url: https://xiaomirom.com/
        - name: MIUI工具箱
          description: 
          url: https://xisentoolbox.cc/
          
    - name: 采集
      sites:
        - name: 量子资源网
          description: 量子资源网-www.lzizy.com-提供在线播放，下载资源采集，全网第一。
          url: http://lzizy.net/
        - name: 非凡资源网
          description: 非凡资源网-www.ffzy.tv-提供在线播放， 在线电影资源网站。
          url: http://www.ffzy.tv/
        - name: 暴风资源
          description: 提供最新最快的视频分享数据
          url: http://bfzy.tv/
        - name: 新浪资源
          description: 新浪资源
          url: https://xinlangzy.com/
        - name: 虎牙资源采集网
          description: 提供最新最快的视频分享数据
          url: http://huyazy.net/
        - name: 金鹰资源采集网
          description: 提供最新最快的视频分享数据
          url: https://jinyingzy.net/
        - name: 光速资源站
          description: 
          url: https://www.guangsuzy.com/
        - name: 速播资源
          description: 速播资源采集站 电影 电视剧 动漫 影视资源一网打尽
          url: https://www.subozy.com/
        - name: 红牛资源
          description: 
          url: https://hongniuzy.net/
        - name: hdzyk
          description: hdzyk,高清资源库,优质资源库
          url: https://www.hdzyk.com/
        - name: 天空资源站
          description: 
          url: https://www.tkzy1.com/
        - name: 闪电资源网
          description: 提供最新最快的视频分享数据
          url: https://www.shandianzy.com/
        - name: 无尽资源网
          description: 
          url: https://wujinzy.com/
        - name: 飞速资源
          description: 飞速资源
          url: https://www.feisuzy.com/
        - name: 淘片资源网
          description: 
          url: https://www.taopianzy.com/index.html
        - name: 云解析资源网
          description: 
          url: https://www.yparse.com/help
